// The episode list. Add one line per new episode (newest at the bottom).
// "file" is the file name inside the episodes/ folder.
// Optional: title_ro / teaser_ro for the Romanian version.
window.EPISODES = [
  { num: 1, title: "The Protein Cookie", file: "001-protein.html", date: "2026-09-25",
    title_ro: "Biscuitul proteic",
    teaser_ro: "Un biscuit cu maiou de sală intră în coșul de cumpărături al lui Dan.",
    teaser: "A cookie wearing a gym shirt walks into Dan's shopping basket." },
  { num: 2, title: "Muscle Fever", file: "002-muscle-fever.html", date: "2026-09-26",
    title_ro: "Febra musculară",
    teaser_ro: "Prima zi de picioare a lui Dan. Două zile mai târziu, scările au păreri.",
    teaser: "Dan's first leg day. Two days later, the stairs have opinions." },
  { num: 3, title: "The CrossFit War", file: "003-crossfit-war.html", date: "2026-09-27",
    title_ro: "Războiul CrossFit",
    teaser_ro: "Dan se înscrie la CrossFit. Flex și Blob se trezesc într-un război pe care nu l-a declarat nimeni.",
    teaser: "Dan joins CrossFit. Flex and Blob wake up in a war nobody declared." },
  { num: 4, title: "The Case of the Angry Shoulder", file: "004-shoulder-case.html", date: "2026-09-28",
    title_ro: "Cazul umărului supărat",
    teaser_ro: "Pe Dan îl doare umărul. Detectivii Flex și Blob preiau cazul.",
    teaser: "Dan's shoulder hurts. Detectives Flex and Blob take the case." },
  { num: 5, title: "Operation Cheat Day", file: "005-operation-cheat-day.html", date: "2026-09-29",
    title_ro: "Operațiunea Cheat Day",
    teaser_ro: "Șase săptămâni de mâncat curat. Flex înflorește. Blob complotează.",
    teaser: "Six weeks of clean eating. Flex is thriving. Blob is plotting." },
  { num: 6, title: "Stick With It", file: "006-stick-with-it.html", date: "2026-09-30",
    title_ro: "Lipit pe viață",
    teaser_ro: "Dan își pune bandă pe genunchi ca un olimpic. Dezlipirea e altă poveste.",
    teaser: "Dan tapes his knees like an Olympian. Taking it off is another story." },
  { num: 7, title: "Hold My Pants", file: "007-hold-my-pants.html", date: "2026-09-30",
    title_ro: "Ține-mă de pantaloni",
    teaser_ro: "Pescuit la crap cu Michael. Minciogul se rupe. Forța prizei lui Dan contează, în sfârșit.",
    teaser: "Carp fishing with Michael. The net breaks. Dan's grip strength finally matters." },
  { num: 8, title: "Train Like a Pro", file: "008-train-like-a-pro.html", date: "2026-10-01",
    title_ro: "Antrenează-te ca un profesionist",
    teaser_ro: "Dan se antrenează cu Seba, numărul 7 din prima divizie de volei a României. Merge exact cum te aștepți.",
    teaser: "Dan trains with Seba, number 7 in Romania's volleyball first division. It goes exactly as well as you think." },
  { num: 9, title: "Mind Over Mattress", file: "009-mind-over-mattress.html", date: "2026-10-05",
    title_ro: "Mai tare decât salteaua",
    teaser_ro: "Dan așteaptă motivația. Creierul explică de ce asta nu merge niciodată, iar Blob îi dă dreptate fără să vrea.",
    teaser: "Dan waits for motivation. The Brain explains why that never works, and Blob accidentally proves it." },
  { num: 10, title: "Deload Week", file: "010-deload-week.html", date: "2026-10-05",
    title_ro: "Săptămâna ușoară",
    teaser_ro: "23 de zile fără pauză. Flex se dezmembrează, Creierul se supraîncălzește, iar Blob e cumva obosit și el.",
    teaser: "23 days without rest. Flex is falling apart, the Brain is overheating, and Blob is somehow tired too." },
  { num: 11, title: "The Village Olympics", file: "011-village-olympics.html", date: "2026-10-05",
    title_ro: "Olimpiada satului",
    teaser_ro: "Dan inventează Țăran Fit: sapă, coasă și găleți de la fântână. Bunica câștigă toate probele.",
    teaser: "Dan invents Țăran Fit: hoe, scythe and well buckets. Bunica wins every event." },
  { num: 12, title: "Zacuscă Season", file: "012-zacusca-season.html", date: "2026-10-07",
    title_ro: "Sezonul de zacuscă",
    teaser_ro: "Dan o ajută pe mama lui să facă zacuscă: 20 de kile de gogoșari, patru ore de amestecat și „un pic de ulei”.",
    teaser: "Dan helps his mother make zacuscă: 20 kilos of peppers, four hours of stirring and \"a little oil.\"" },
  { num: 13, title: "Grape Expectations", file: "013-grape-expectations.html", date: "2026-10-09",
    title_ro: "Din vie în butoi",
    teaser_ro: "Dan o ajută pe mama la cules: 40 de rânduri de vie, 600 de aplecări, struguri călcați desculț și „e doar suc, e sănătos”.",
    teaser: "Dan helps Mama with the grape harvest: 40 rows of vines, 600 squats, barefoot grape stomping and \"it's just juice, it's healthy.\"" },
  { num: 14, title: "Door Day", file: "014-door-day.html", date: "2026-10-10",
    title_ro: "Forțând nota",
    teaser_ro: "Dan ajunge devreme, antrenoarea întârzie, iar ușa sălii pierde lupta. Apoi apare Ana.",
    teaser: "Dan arrives early, the coach is late, and the gym door loses a fight. Then Coach Ana shows up." },
];
