// The episode list. Add one line per new episode (newest at the bottom).
// "file" is the file name inside the episodes/ folder.
window.EPISODES = [
  { num: 1, title: "The Protein Cookie", file: "001-protein.html", date: "2026-09-25",
    teaser: "A cookie wearing a gym shirt walks into Dan's shopping basket." },
  { num: 2, title: "Muscle Fever", file: "002-muscle-fever.html", date: "2026-09-26",
    teaser: "Dan's first leg day. Two days later, the stairs have opinions." },
  { num: 3, title: "The CrossFit War", file: "003-crossfit-war.html", date: "2026-09-27",
    teaser: "Dan joins CrossFit. Flex and Blob wake up in a war nobody declared." },
  { num: 4, title: "The Case of the Angry Shoulder", file: "004-shoulder-case.html", date: "2026-09-28",
    teaser: "Dan's shoulder hurts. Detectives Flex and Blob take the case." },
  { num: 5, title: "Operation Cheat Day", file: "005-operation-cheat-day.html", date: "2026-09-29",
    teaser: "Six weeks of clean eating. Flex is thriving. Blob is plotting." },
  { num: 6, title: "Stick With It", file: "006-stick-with-it.html", date: "2026-09-30",
    teaser: "Dan tapes his knees like an Olympian. Taking it off is another story." },
  { num: 7, title: "Hold My Pants", file: "007-hold-my-pants.html", date: "2026-09-30",
    teaser: "Carp fishing with Michael. The net breaks. Dan's grip strength finally matters." },
  { num: 8, title: "Train Like a Pro", file: "008-train-like-a-pro.html", date: "2026-10-01",
    teaser: "Dan trains with Seba, number 7 in Romania's volleyball first division. It goes exactly as well as you think." },
  { num: 9, title: "Mind Over Mattress", file: "009-mind-over-mattress.html", date: "2026-10-05",
    teaser: "Dan waits for motivation. The Brain explains why that never works, and Blob accidentally proves it." },
  { num: 10, title: "Deload Week", file: "010-deload-week.html", date: "2026-10-05",
    teaser: "23 days without rest. Flex is falling apart, the Brain is overheating, and Blob is somehow tired too." },
  { num: 11, title: "The Village Olympics", file: "011-village-olympics.html", date: "2026-10-05",
    teaser: "Dan invents Țăran Fit: hoe, scythe and well buckets. Bunica wins every event." },
  { num: 12, title: "Zacuscă Season", file: "012-zacusca-season.html", date: "2026-10-07",
    teaser: "Dan helps his mother make zacuscă: 20 kilos of peppers, four hours of stirring and \"a little oil.\"" },
];
